name: Build and Upload vdb5

on:
  schedule:
    - cron: "20 */12 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/vdb

jobs:
  builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/checkout-vdb-dependencies
        with:
          vulnerability-db-ref: v5.8.2
          vuln-list-path: vuln-list

      - uses: ./.github/actions/setup-vdb-build-tools
        with:
          install-nydus: "true"

      - name: Build and upload db - 2020
        uses: ./.github/actions/build-and-upload-vdb5
        with:
          vuln-list-path: vuln-list
          image-repo: appthreat/vdb
          image-gz-repo: appthreat/vdbgz
          image-xz-repo: appthreat/vdbxz
          rafs-blob-id: appthreat-vdb-v5
          nvd-start-year: "2020"
          github-page-count: "10"
          use-config-annotation: "true"
          config-file: ../config.json
          annotation-file: ../annotations.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          PYTHONPATH: vulnerability-db

      - uses: ./.github/actions/checkout-vdb-dependencies
        with:
          checkout-vulnerability-db: "false"
          vuln-list-path: vuln-list2

      - name: Build and upload db - 2016
        uses: ./.github/actions/build-and-upload-vdb5
        with:
          vuln-list-path: vuln-list2
          image-repo: appthreat/vdb-10y
          image-gz-repo: appthreat/vdbgz-10y
          image-xz-repo: appthreat/vdbxz-10y
          rafs-blob-id: appthreat-vdb-10y-v5
          nvd-start-year: "2016"
          github-page-count: "20"
          clean-workspace: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          PYTHONPATH: vulnerability-db
