name: Build and Upload app only vdb5

on:
  schedule:
    - cron: "10 */12 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/vdb

jobs:
  builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/checkout-vdb-dependencies
        with:
          vulnerability-db-ref: v5.8.2
          vuln-list-path: vuln-list
          vuln-list-sparse-checkout: |
            nvd/2020
            nvd/2021
            nvd/2022
            nvd/2023
            nvd/2024
            nvd/2025
            nvd/2026

      - uses: ./.github/actions/setup-vdb-build-tools
        with:
          install-nydus: "true"

      - name: Build and upload db - 2020
        uses: ./.github/actions/build-and-upload-vdb5
        with:
          vuln-list-path: vuln-list
          image-repo: appthreat/vdb-app
          image-gz-repo: appthreat/vdbgz-app
          image-xz-repo: appthreat/vdbxz-app
          rafs-blob-id: appthreat-vdb-v5
          nvd-start-year: "2020"
          github-page-count: "10"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          PYTHONPATH: vulnerability-db
          OSV_EXCLUDE_MALWARE: true
          VDB_IGNORE_ALMALINUX: true
          VDB_IGNORE_ALPINE: true
          VDB_IGNORE_DEBIAN: true
          VDB_IGNORE_ROCKYLINUX: true

      - uses: ./.github/actions/checkout-vdb-dependencies
        with:
          checkout-vulnerability-db: "false"
          vuln-list-path: vuln-list2
          vuln-list-sparse-checkout: |
            nvd/2016
            nvd/2017
            nvd/2018
            nvd/2019
            nvd/2020
            nvd/2021
            nvd/2022
            nvd/2023
            nvd/2024
            nvd/2025
            nvd/2026

      - name: Build and upload db - 2016
        uses: ./.github/actions/build-and-upload-vdb5
        with:
          vuln-list-path: vuln-list2
          image-repo: appthreat/vdb-app-10y
          image-gz-repo: appthreat/vdbgz-app-10y
          image-xz-repo: appthreat/vdbxz-app-10y
          rafs-blob-id: appthreat-vdb-10y-v5
          nvd-start-year: "2016"
          github-page-count: "20"
          clean-workspace: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          PYTHONPATH: vulnerability-db
          OSV_EXCLUDE_MALWARE: true
          VDB_IGNORE_ALMALINUX: true
          VDB_IGNORE_ALPINE: true
          VDB_IGNORE_DEBIAN: true
          VDB_IGNORE_ROCKYLINUX: true
