name: Build and Upload vdb 6.5.x

on:
  schedule:
    - cron: "20 */12 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/vdb

jobs:
  app_2y_builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      GITHUB_PAGE_COUNT: 10
      NVD_START_YEAR: 2024
      VDB_IGNORE_OS: true
      VDB_METADATA_APP_ONLY: true
      VDB_IGNORE_ALMALINUX: true
      VDB_IGNORE_ALPINE: true
      VDB_IGNORE_DEBIAN: true
      VDB_IGNORE_ROCKYLINUX: true
    steps:
      - uses: ./.github/actions/setup-vdb
        with:
          nvd-years: "nvd/2024\nnvd/2025\nnvd/2026"
      - uses: ./.github/actions/build-upload-vdb
        with:
          xz-image-name: vdbxz-app-2y
          zst-image-name: vdbzst-app-2y
          hf-path: app-2y
        continue-on-error: true

  app_builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      GITHUB_PAGE_COUNT: 30
      NVD_START_YEAR: 2020
      VDB_IGNORE_OS: true
      VDB_METADATA_APP_ONLY: true
      VDB_IGNORE_ALMALINUX: true
      VDB_IGNORE_ALPINE: true
      VDB_IGNORE_DEBIAN: true
      VDB_IGNORE_ROCKYLINUX: true
    steps:
      - uses: ./.github/actions/setup-vdb
        with:
          nvd-years: "nvd/2020\nnvd/2021\nnvd/2022\nnvd/2023\nnvd/2024\nnvd/2025\nnvd/2026"
      - uses: ./.github/actions/build-upload-vdb
        with:
          xz-image-name: vdbxz-app
          zst-image-name: vdbzst-app
          hf-path: app
        continue-on-error: true

  app_10y_builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      GITHUB_PAGE_COUNT: 30
      NVD_START_YEAR: 2020
      VDB_IGNORE_OS: true
      VDB_METADATA_APP_ONLY: true
      VDB_IGNORE_ALMALINUX: true
      VDB_IGNORE_ALPINE: true
      VDB_IGNORE_DEBIAN: true
      VDB_IGNORE_ROCKYLINUX: true
    steps:
      - uses: ./.github/actions/setup-vdb
        with:
          nvd-years: "nvd/2016\nnvd/2017\nnvd/2018\nnvd/2019\nnvd/2020\nnvd/2021\nnvd/2022\nnvd/2023\nnvd/2024\nnvd/2025\nnvd/2026"
      - uses: ./.github/actions/build-upload-vdb
        with:
          xz-image-name: vdbxz-app-10y
          zst-image-name: vdbzst-app-10y
          hf-path: app-10y
        continue-on-error: true

  os_builder:
    runs-on: [self-hosted-ubuntu, linux]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: ./.github/actions/setup-vdb
        with:
          sparse-checkout: 'false'
          self-hosted: 'true'
      - uses: ./.github/actions/build-upload-vdb
        with:
          xz-image-name: vdbxz
          zst-image-name: vdbzst
          hf-path: app-os
          self-hosted: 'true'
          os-exclude-dirs: 'kevc mariner cvrf/suse/suse'
        env:
          GITHUB_PAGE_COUNT: 10
          NVD_START_YEAR: 2020
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: AppThreat/vuln-list
          path: vuln-list-10y
          fetch-depth: '1'
          persist-credentials: false
      - name: Build and upload VDB 10y
        run: |
          echo $GITHUB_TOKEN | oras login ghcr.io -u $GITHUB_USERNAME --password-stdin
          cd $GITHUB_WORKSPACE
          rm -rf vdb_data vdb_cache
          mkdir vdb_data vdb_cache
          rm -rf ./vuln-list-10y/kevc ./vuln-list-10y/mariner ./vuln-list-10y/cvrf/suse/suse
          zip -q -r vuln-list.zip ./vuln-list-10y/
          mv vuln-list.zip vdb_cache/
          rm -rf ./vuln-list-10y/
          python3 vulnerability-db/vdb/cli.py --cache-os
          ls -lh vdb_data
          ls -lh vdb_cache
          cd vdb_data
          tar -cvJf data.vdb6.tar.xz data.vdb6
          tar -cvJf data.index.vdb6.tar.xz data.index.vdb6
          oras push ghcr.io/appthreat/vdbxz-10y:v6.5.x \
            --artifact-type application/vnd.oras.config.v1+json \
            ./vdb.meta:application/vnd.appthreat.vdb.config.v1+json \
            ./data.vdb6.tar.xz:application/vnd.appthreat.vdb.layer.v1+tar \
            ./data.index.vdb6.tar.xz:application/vnd.appthreat.vdb.layer.v1+tar
          oras tag ghcr.io/appthreat/vdbxz-10y:v6.5.x v6
          hf upload --quiet --repo-type dataset --delete app-os-10y/*.tar.xz AppThreat/vdb ./data.vdb6.tar.xz app-os-10y/data.vdb6.tar.xz
          hf upload --quiet --repo-type dataset AppThreat/vdb ./data.index.vdb6.tar.xz app-os-10y/data.index.vdb6.tar.xz
          zstd --ultra data.index.vdb6
          zstd --ultra data.vdb6
          oras push ghcr.io/appthreat/vdbzst-10y:v6.5.x \
            --artifact-type application/vnd.oras.config.v1+json \
            ./vdb.meta:application/vnd.appthreat.vdb.config.v1+json \
            ./data.vdb6.zst:application/vnd.appthreat.vdb.layer.v1+zst \
            ./data.index.vdb6.zst:application/vnd.appthreat.vdb.layer.v1+zst
          oras tag ghcr.io/appthreat/vdbzst-10y:v6.5.x v6
          hf upload --quiet --repo-type dataset --delete app-os-10y/*.zst AppThreat/vdb ./data.vdb6.zst app-os-10y/data.vdb6.zst
          hf upload --quiet --repo-type dataset AppThreat/vdb ./data.index.vdb6.zst app-os-10y/data.index.vdb6.zst
          hf upload --quiet --repo-type dataset --delete app-os-10y/*.vdb6 AppThreat/vdb ./data.vdb6 app-os-10y/data.vdb6
          hf upload --quiet --repo-type dataset AppThreat/vdb ./data.index.vdb6 app-os-10y/data.index.vdb6
          hf upload --quiet --repo-type dataset AppThreat/vdb ./vdb.meta app-os-10y/vdb.meta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONPATH: vulnerability-db
          VDB_HOME: vdb_data
          VDB_CACHE: vdb_cache
          GITHUB_PAGE_COUNT: 20
          NVD_START_YEAR: 2016
          GITHUB_USERNAME: ${{ github.actor }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
