name: Build and Upload purl2cpe

on:
  schedule:
  - cron: "0 */8 * * *"
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/purl2cpe

jobs:
  builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: scanoss/purl2cpe
        path: purl2cpe
        fetch-depth: '1'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Trim CI agent
      run: |
        chmod +x contrib/free_disk_space.sh
        ./contrib/free_disk_space.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install PyYaml tqdm
    - name: Build database
      run: |
        python purl2cpe/utilities/sqlite_loader.py purl2cpe/data -o purl2cpe.db --quiet
        rm -rf purl2cpe
        zstd --ultra purl2cpe.db
        tar -cvJf purl2cpe.db.tar.xz purl2cpe.db
        ls -lh
        echo $GITHUB_TOKEN | oras login ghcr.io -u $GITHUB_USERNAME --password-stdin
        oras push ghcr.io/appthreat/purl2cpezst:v1 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./purl2cpe.db.zst:application/vnd.appthreat.vdb.layer.v1+zst
        oras push ghcr.io/appthreat/purl2cpexz:v1 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./purl2cpe.db.tar.xz:application/vnd.appthreat.vdb.layer.v1+tar
        oras push ghcr.io/$IMAGE_NAME:v1 \
          --config ./config-purl.json:application/vnd.oras.config.v1+json \
          --annotation-file ./annotations-purl.json \
          ./purl2cpe.db:application/vnd.appthreat.purl2cpe.layer.v1+tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
